
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.440287
  longitude: -80.534465
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
#introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

frontend:
   themes: !include themes.yaml     

#discovery:
logbook:
  include:      
   entities:
     - sensor.last_boot     


#glances system monitor
sensor:
  - platform: glances
    host: 192.168.0.177
    resources:
      - 'disk_use_percent'

        
# Sensors
sensor:
  # Weather prediction
  - platform: darksky
    api_key: 
    monitored_conditions:
      - icon
      - summary
#      - nearest_storm_distance
#      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
           minutes: 5

   

# switches
tuya:
   username: @gmail.com
   password: 
   country_code: 1
   platform: smart_life

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.0.158/webcam/?action=snapshot
    mjpeg_url: http://192.168.0.158/webcam/?action=stream
  
  - platform: foscam 
    ip: 192.168.0.184
    username: admin
    password:

  - platform: foscam 
    ip: 192.168.0.185
    username: admin
    password: 

  - platform: mjpeg
    name: triffid
    mjpeg_url: http://192.168.0.155:8081/    


media_player:
  - platform: volumio
    host: 192.168.0.150
    port: 3000


#media extractor youtube
media_extractor:



#presence

#mqtt server
#mqtt:
#  password: hello


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
